Neos:
  ContentRepository:
    Debug:
      explore:
        menuColumns:
          10:
            groups:
              - Workspace
              - Dimensions

          20:
            groups:
              - Nodes
          30:
            groups:
              - ContentRepository
              - Events

          40:
            groups:
              - Other
